name: Daily Task Email

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 06:00 GMT
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai gspread oauth2client pandas

      - name: Run task assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        run: |
          python amy_to_do_list.py
